### ISSUE TITLE
Material Theme Color changes depend on lockscreen wallpaper

### ISSUE THREAD

**Issue by Ansarmughal99** [itsmartashub/floristyle#10]
### Prerequisites (Required)

- [X] I [searched for any existing report](https://github.com/itsmartashub/floristyle/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Bug Description (Required)

Whenever the Lockscreen Wallpaper change. The Material theme Change with respect to the color of Wallpaper. While it should deoend on HomeScreen or App Drawer Wallpaper Color 

### Steps to reproduce

1. Material Theme. Depend on lockscreen color

### Expected Behavior (Required)

It Should depend on Theme set of keyboard or the HomeScreen or App Drawer

### Actual Behavior (Required)

Material theme Depend on Lockscreen Wallpaper

### FlorisBoard Version (Required)

0.4.0 Beta 2

### Gboardish version (Required)

3.0

### Android version (Required)

Android 13

### Device (Required)

Realme gt neo 2

### Screenshots or Videos (Optional)

![Screenshot_2024-04-27-21-47-49-80_c853220993b0ed55eb2e57645fcd343d](https://github.com/itsmartashub/floristyle/assets/74392407/0c774d3f-cade-4296-bb29-e276dd27076f)

**Comment by itsmartashub** [comment]
Hey there. I was wondering if there's a chance you could answer a few questions I have:

1. Could you pass me the **source** that states Material You necessarily depends on the lock screen wallpaper?
2. Could you let me know if the Material You **in the system** matches the Material You **in Florisboard**?

From what I've tested on a few different ROMs, it seems that Material You depends on the **last set** image, whether it's set for the home screen, lock screen, both, or even manually set Material You palettes offered in the system settings. I came across this information somewhere about this: _**"Last one is a winner."**_ I'm not sure if Material You behaves differently in different ROMs.

Anyway, the theme creator can't influence this. The theme creator only creates themes based on already generated Material You colour palettes. If this still bothers you, maybe it'd be better to open an issue on the [Florisboard](https://github.com/florisboard/florisboard/issues)
