### ISSUE TITLE
Black enter key on monochrome theme

### ISSUE THREAD

**Issue by M00NJ** [itsmartashub/floristyle#12]
### Prerequisites (Required)

- [X] I [searched for any existing report](https://github.com/itsmartashub/floristyle/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Bug Description (Required)

When using a monochrome system accent color the enter button is black, making it harder to see. This is especially problematic for the darker and OLED themes, since the button is completely invisible then. I think a similar color to the number button would make sense here.

### Steps to reproduce

1. Select a monochrome accent color in the device settings (If there is no such option, use a black wallpaper)
2. Select any of the dark, darker or OLED themes
3. The enter button ist black

### Expected Behavior (Required)

The enter button has a lighter color

### Actual Behavior (Required)

The enter button is black

### FlorisBoard Version (Required)

v0.4.0-beta02

### Gboardish version (Required)

v3.0.1

### Android version (Required)

Android 14 (GOS)

### Device (Required)

Pixel 4a 5g

### Screenshots or Videos (Optional)

![Screenshot_20240717-162345](https://github.com/user-attachments/assets/01870e92-be93-4f90-865e-1cd24fc1d56c)

![Screenshot_20240717-162428](https://github.com/user-attachments/assets/f91ddd4a-a466-4030-867a-44d998ecbc1f)

**Comment by itsmartashub** [comment]
Hey @M00NJ , thank you for opening this issue. Unfortunately, I'm not in a position to investigate the bug at the moment. I anticipate that I'll be able to return to this issue in about three weeks. 

In the meantime, you can manually fix the issue by going into the theme editor for the broken themes and set the color that fits your needs, if you haven't already. If you need a small guide on how to do this, please let me know.

I appreciate your patience and understanding.

**Comment by M00NJ** [comment]
No worries, there is no urgency here :) Thanks for the theme editor hint, I forgot about that.
