### ISSUE TITLE
[BUG] Color names need to be updated

### ISSUE THREAD

**Issue by Fxsch** [itsmartashub/floristyle#9]
### Prerequisites (Required)

- [X] I [searched for any existing report](https://github.com/itsmartashub/floristyle/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Bug Description (Required)

With the [new beta release of FlorisBoard](https://github.com/florisboard/florisboard/releases/tag/v0.4.0-beta02), the surface color names have been changed and need to be updated. The colors of this theme look completely wrong after updating to that version.

### Steps to reproduce

1. Update FlorisBoard to v0.4.0-beta02

### Expected Behavior (Required)

Correct colors

### Actual Behavior (Required)

Wrong colors

### FlorisBoard Version (Required)

v0.4.0-beta02

### Gboardish version (Required)

v2.1.2

### Android version (Required)

Android 13

### Device (Required)

Nothing Phone (1)

**Comment by itsmartashub** [comment]
Yap, I'm aware of that, `surface` has been removed and replaced with `surfaceBright` (for light schemes) and `surfaceDim` (for dark schemes). It's a WIP (work in progress), so the update will arrive today or tomorrow after thorough testing of all themes on A14 as well. I kindly ask for patience and understanding. Thank you for using Floristyle.
